name = "PascalVocTools"
uuid = "3fdd8fd9-3429-41df-93e4-b1e51c23000a"
version = "0.0.3"
authors = ["Ciro B Rosa <ciro.rosa@alumni.usp.br>"]

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"

[compat]
Downloads = "1.6 - 1.7"
Images = "0.24 - 0.26"
julia = "1.10 - 1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
